language: python

python:
  - "3.5"
  - "3.5-dev"
  - "nightly"

sudo: required

env:
  global:
  - PGPORT=5433
  - PGHOST=localhost
  - DATABASE_URL=postgres://postgres@localhost:5433/aiotpt

services:
  - postgresql

# addons:
#   postgresql: "9.5"
#
# before_script:
#   - psql -U postgres -c 'create database aiotpt;'
#   - psql -f schema.sql -U postgres

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database aiotpt;'
  - psql -f schema.sql

install:
  - pip install -r requirements.txt
  - pip install pytest-travis-fold

script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
